SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS 'TOTAL_SALES'
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE Month(C.SALES_DATE) = '1'
GROUP BY B.AUTHOR_ID, A.CATEGORY
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC;